spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://exercise-db:5432/postgres
    username: postgres
    password: azsuth
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    # properties:
    #   javax:
    #     persistence:
    #       schema-generation:
    #         create-source: metadata
    #         scripts:
    #           action: create
    #           create-target: create.sql
