spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: azsuth
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    org.springframework: ERROR
    com.azs.beefygainz.exercise: DEBUG      
